### ISSUE TITLE
Exporter: Export of scene fails

### ISSUE THREAD

**Issue by akdd11** [mitsuba-renderer/mitsuba-blender#55]
**Exporting a Scene in Mitsuba Format Fails**

**Bug Description**
I want to export a scene in the Mitsuba format to import it to another Python tool. When trying to export a scene, there is an error and the scene is not saved. This happens already with the default Blender scene.

**To Reproduce**
1. Opening Blender
2. Save file. (does not have an impact, also tried to directly export)
3. File > Export > Mitsuba 2

The error message is the following:

Python: Traceback (most recent call last):
```
  File "C:\Blender\blender-3.4.1-windows-x64\3.4\scripts\addons\mitsuba2-blender\export.py", line 112, in execute
    self.export_ctx.set_filename(self.filepath, split_files=self.split_files)
  File "C:\Blender\blender-3.4.1-windows-x64\3.4\scripts\addons\mitsuba2-blender\file_api.py", line 100, in set_filename
    self.xml_writer = WriteXML(name, split_files)
  File "C:\Blender\blender-3.4.1-windows-x64\3.4\python\lib\site-packages\mitsuba\python\xml.py", line 62, in __init__
    self.set_filename(path)
  File "C:\Blender\blender-3.4.1-windows-x64\3.4\python\lib\site-packages\mitsuba\python\xml.py", line 167, in set_filename
    self.textures_folder = os.path.join(self.directory, self.subfolders['texture'])
TypeError: 'bool' object is not subscriptable
```

I tried different filenames and paths, one example is C:\Blender\scenes\scene1.xml. Dialog configuration as below, but also different options do not seem to have an impact.
![image](https://user-images.githubusercontent.com/54317618/228212088-7153e000-0390-4a2b-8629-c6e6914f59d7.png)

**Environment (please complete the following information):**
 - OS: Windows 11
 - Blender Version: 3.4.1
 - Add-on Version: latest
 - Mitsuba installed via pip

**Comment by akdd11** [comment]
Hi,

thank you very much for the fast reply! Indeed, I had installed the old version. -- No problem anymore.
