### ISSUE TITLE
<Mitsuba blender add on error>: <Cannot install Mitsuba add-on in blender>

### ISSUE THREAD

**Issue by Pooja-M9** [mitsuba-renderer/mitsuba-blender#57]
**Cannot install mitsuba add on for blender**

**Bug Description**
While trying to install mitsuba add-on in blender, i am getting following error:

Read prefs: C:\Users\MOH80574\AppData\Roaming\Blender Foundation\Blender\3.5\config\userpref.blend
Exception in module register(): C:\Users\MOH80574\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\mitsuba-blender\__init__.py
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.5\3.5\python\lib\site-packages\mitsuba\__init__.py", line 49, in <module>
    _import('mitsuba.mitsuba_ext')
  File "C:\Program Files\Blender Foundation\Blender 3.5\3.5\python\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 674, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 571, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 1176, in create_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
ImportError: DLL load failed while importing mitsuba_ext: The specified procedure could not be found.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.5\3.5\scripts\modules\addon_utils.py", line 369, in enable
    mod.register()
  File "C:\Users\MOH80574\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\mitsuba-blender\__init__.py", line 301, in register
    if try_register_mitsuba(context):
  File "C:\Users\MOH80574\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\mitsuba-blender\__init__.py", line 55, in try_register_mitsuba
    could_init_mitsuba = init_mitsuba(context)
  File "C:\Users\MOH80574\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\mitsuba-blender\__init__.py", line 35, in init_mitsuba
    import mitsuba
  File "C:\Program Files\Blender Foundation\Blender 3.5\3.5\python\lib\site-packages\mitsuba\__init__.py", line 69, in <module>
    raise exc
ImportError: The 'mitsuba' native modules could not be imported. You're likely trying to use Mitsuba within a Python binary (C:\Program Files\Blender Foundation\Blender 3.5\3.5\python\bin\python.exe) that is different from the one for which the native module was compiled (C:\Users\runneradmin\AppData\Local\Temp\cibw-run-rwptb42b\cp310-win_amd64\build\venv\Scripts\python.exe).

**To Reproduce**
1. Download blender and mitsuba add on from these two links - https://www.blender.org/download/releases/3-5/ and https://github.com/mitsuba-renderer/mitsuba-blender 
2. Open blender and click on edit -> preferences -> install -> mitsuba zip file
3. Error is popped up when activating the add-on 

**Expected behavior**
While activating, mitsuba add-on should be activated without any issue

**Environment (please complete the following information):**
 - OS: [Windows]
 - Blender Version: [3.5]
 - Add-on Version: [latest]

**Comment by bathal1** [comment]
Did you download the `mitsuba-blender.zip` file from the [Releases](https://github.com/mitsuba-renderer/mitsuba-blender/releases/tag/latest) page ?

**Comment by bathal1** [comment]
The addon does not have a field for a mitsuba zip file. You can either let blender's python install mitsuba through pip by clicking on `Install dependencies` (I recommend doing that) or point to a local mitsuba build folder in `Advanced settings`

**Comment by bathal1** [comment]
Could you try reinstalling the addon from scratch, and see if the option is available then ? To uninstall the addon, click on "remove". You can then reload blender and install the addon from the zip file as you did before.

**Comment by Pooja-M9** [comment]
I have removed the zip file and then reinstalled it again. Now i cant see the dependencies option at all.
![image](https://user-images.githubusercontent.com/84560996/229146300-cc9046bb-b169-419d-8de1-7d6c09cecc1d.png)

**Comment by Pooja-M9** [comment]
When i click on the activate button, error pops up as i showed before - 
![image](https://user-images.githubusercontent.com/84560996/229155078-28305b25-0b32-45fb-8e84-745bdcc0abba.png)

**Comment by Pooja-M9** [comment]
Hello,

I have copied the full error log as you advised:

Read prefs: C:\Users\MOH80574\AppData\Roaming\Blender Foundation\Blender\3.5\config\userpref.blend
Exception in module register(): C:\Users\MOH80574\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\mitsuba-blender\__init__.py
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.5\3.5\python\lib\site-packages\mitsuba\__init__.py", line 49, in <module>
    _import('mitsuba.mitsuba_ext')
  File "C:\Program Files\Blender Foundation\Blender 3.5\3.5\python\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 674, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 571, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 1176, in create_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
ImportError: DLL load failed while importing mitsuba_ext: The specified procedure could not be found.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.5\3.5\scripts\modules\addon_utils.py", line 369, in enable
    mod.register()
  File "C:\Users\MOH80574\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\mitsuba-blender\__init__.py", line 301, in register
    if try_register_mitsuba(context):
  File "C:\Users\MOH80574\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\mitsuba-blender\__init__.py", line 67, in try_register_mitsuba
    could_init_mitsuba = init_mitsuba(context)
  File "C:\Users\MOH80574\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\mitsuba-blender\__init__.py", line 35, in init_mitsuba
    import mitsuba
  File "C:\Program Files\Blender Foundation\Blender 3.5\3.5\python\lib\site-packages\mitsuba\__init__.py", line 69, in <module>
    raise exc
ImportError: The 'mitsuba' native modules could not be imported. You're likely trying to use Mitsuba within a Python binary (C:\Program Files\Blender Foundation\Blender 3.5\3.5\python\bin\python.exe) that is different from the one for which the native module was compiled (C:\Users\runneradmin\AppData\Local\Temp\cibw-run-rwptb42b\cp310-win_amd64\build\venv\Scripts\python.exe).

Exception in module register(): C:\Users\MOH80574\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\mitsuba-blender\__init__.py
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.5\3.5\python\lib\site-packages\mitsuba\__init__.py", line 49, in <module>
    _import('mitsuba.mitsuba_ext')
  File "C:\Program Files\Blender Foundation\Blender 3.5\3.5\python\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 674, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 571, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 1176, in create_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
ImportError: DLL load failed while importing mitsuba_ext: The specified procedure could not be found.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.5\3.5\scripts\modules\addon_utils.py", line 369, in enable
    mod.register()
  File "C:\Users\MOH80574\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\mitsuba-blender\__init__.py", line 301, in register
    if try_register_mitsuba(context):
  File "C:\Users\MOH80574\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\mitsuba-blender\__init__.py", line 67, in try_register_mitsuba
    could_init_mitsuba = init_mitsuba(context)
  File "C:\Users\MOH80574\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\mitsuba-blender\__init__.py", line 35, in init_mitsuba
    import mitsuba
  File "C:\Program Files\Blender Foundation\Blender 3.5\3.5\python\lib\site-packages\mitsuba\__init__.py", line 69, in <module>
    raise exc
ImportError: The 'mitsuba' native modules could not be imported. You're likely trying to use Mitsuba within a Python binary (C:\Program Files\Blender Foundation\Blender 3.5\3.5\python\bin\python.exe) that is different from the one for which the native module was compiled (C:\Users\runneradmin\AppData\Local\Temp\cibw-run-rwptb42b\cp310-win_amd64\build\venv\Scripts\python.exe).

**Comment by isalyahova** [comment]
@bathal1, I have the same error :(

**Comment by Lumi0706** [comment]
Hello, I also encountered this problem, is there a solution now?

**Comment by Pooja-M9** [comment]
Unfortunately, it hasnt been resolved till now

**Comment by Mysakshi2104** [comment]
I am facing the same issue.....is this resolved??
